services:
  php-apache-environment:
    container_name: php-apache
    build:
      dockerfile: Dockerfile
    depends_on:
      - mysql
    volumes:
      - ./public:/var/www/html         # ← ไฟล์หน้าเว็บ
      - ./src:/var/www/src             # ← โค้ด PHP ฟังก์ชัน/DB
      - ./templates:/var/www/templates # ← header/footer
    ports:
      - 80:80
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: myappdb
      MYSQL_USER: myapp
      MYSQL_PASSWORD: myapp1234
    volumes:
      - ./init_scripts:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
    - "8080:80"
    restart: always
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql